services:
  postgres:
    container_name: postgres_container
    image: timescale/timescaledb-ha:pg15.7-ts2.15.0-all
    environment:
      POSTGRES_MULTIPLE_DATABASES: "base_1,base_2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      TIMESCALEDB_TELEMETRY: "off"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U marintel_user -d marintel_db"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind

